[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "~1.5.0"

[[constraint]]
  name = "github.com/mostafah/fsync"
  branch = "master"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "~0.3.0"

[prune]
  go-tests = true
  unused-packages = true
