fixLink = "/"
languageCode = "zh-CN"
theme = "default"
suffixTitle = " - EasyDoc"
homeTitle = "EasyDoc 官网 | EasyDoc Website"
# SCANFILE: The local path begins with src(base on src directory). support external link.
scanFile = [
    ["首页 | Home", "src/index.md"],
    ["下载 | Download", "src/download/index.md"],
    ["EasyDoc 的使用", "src/zh-cn/index.md"],
    ["关于 EasyDoc", "src/zh-cn/info.md"],
    ["EasyDoc 的更新日志", "src/zh-cn/log.md"],
    ["EasyDoc Use", "src/en/index.md"],
    ["About EasyDoc", "src/en/info.md"],
    ["EasyDoc Update Log", "src/en/log.md"],
    ["v1 旧版本使用说明", "src/v1/zh-cn/index.md"],
    ["v1 old version instructions", "src/v1/en/index.md"],
]
